# syntax: training.win_rate or testing.total
sort_by: 'training.serenity_index'

filter_dna:
  training:
    total:
      min: None
      max: None
    win_rate:
      min: None
      max: None
    ratio_avg_win_loss:
      min: None
      max: None
    longs_count:
      min: None
      max: None
    longs_percentage:
      min: None
      max: None
    short_percentage:
      min: None
      max: None
    shorts_count:
      min: None
      max: None
    net_profit_percentage:
      min: None
      max: None
    expectancy_percentage:
      min: None
      max: None
    annual_return:
      min: None
      max: None
    sharpe_ratio:
      min: None
      max: None
    calmar_ratio:
      min: None
      max: None
    sortino_ratio:
      min: None
      max: None
    omega_ratio:
      min: None
      max: None
    serenity_index:
      min: None
      max: None
    smart_sharpe:
      min: None
      max: None
    smart_sortino:
      min: None
      max: None
    winning_streak:
      min: None
      max: None
    losing_streak:
      min: None
      max: None
    largest_losing_trade:
      min: None
      max: None
    largest_winning_trade:
      min: None
      max: None
  testing:
    total:
      min: None
      max: None
    win_rate:
      min: None
      max: None
    ratio_avg_win_loss:
      min: None
      max: None
    longs_count:
      min: None
      max: None
    longs_percentage:
      min: None
      max: None
    short_percentage:
      min: None
      max: None
    shorts_count:
      min: None
      max: None
    net_profit_percentage:
      min: None
      max: None
    expectancy_percentage:
      min: None
      max: None
    annual_return:
      min: None
      max: None
    sharpe_ratio:
      min: None
      max: None
    calmar_ratio:
      min: None
      max: None
    sortino_ratio:
      min: None
      max: None
    omega_ratio:
      min: None
      max: None
    serenity_index:
      min: None
      max: None
    smart_sharpe:
      min: None
      max: None
    smart_sortino:
      min: None
      max: None
    winning_streak:
      min: None
      max: None
    losing_streak:
      min: None
      max: None
    largest_losing_trade:
      min: None
      max: None
    largest_winning_trade:
      min: None
      max: None

backtest-data:
  starting_balance: 5000
  fee: 0.001
  futures_leverage: 1
  futures_leverage_mode: cross
  settlement_currency: USDT
  warm_up_candles: 240
  exchange: Binance
  symbols:
    - 'BTC-USDT'
    - 'BNB-USDT'
  timeframes:
    - '1h'
    - '2h'
  timespans:
    0:
      start_date: '2020-01-01'
      finish_date: '2021-01-01'
    1:
      start_date: '2021-01-01'
      finish_date: '2021-11-09'
  extra_routes:
    0:
      exchange: 'Binance'
      symbol: 'BTC-USDT'
      timeframe: '1D'
    1:
      exchange: 'Binance'
      symbol: 'BNB-USDT'
      timeframe: '1D'

